version: '3'

services:
  api:
    build:
      context: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    restart: always
    volumes:
      - ./video:/usr/src/app/video
    # env_file:
      # - .env
    # networks:
      # - api_network
    # depends_on:
      # - mongodb
  # mongodb:
    # image: mongo:5.0
    # ports:
      # - 27017:27017
    # restart: always
    # volumes:
      # - ./data:/data/db
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      # - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
# networks:
  # api_network:
